### ISSUE TITLE
Pash error in a script that append elements to array.

### ISSUE THREAD

**Issue by tammam1998** [binpash/pash#385]
The following piece of code, which appends an element to an array, throws an error in pash but in bash
```
while read s_line;
do
	arr[${#arr[*]}]="$s_line"
done < ${IN}/${IN_NAME}
```

The error
```
Missing CTLENDVAR for VSNORMAL/VSLENGTH
Traceback (most recent call last):
  File "/home/tammam1/pash/compiler/pash.py", line 247, in <module>
    main()
  File "/home/tammam1/pash/compiler/pash.py", line 30, in main
    ast_objects = parse_shell_to_asts(input_script_path)
  File "/home/tammam1/pash/compiler/parse.py", line 21, in parse_shell_to_asts
    return list(new_ast_objects)
  File "/home/tammam1/pash/compiler/parser/ceda/parse_to_ast2.py", line 84, in parse_to_ast
    new_ast = of_node (n_ptr)
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 141, in of_node
    return ["Redir", of_nredir (n)];
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 157, in of_nredir
    return ([n.nredir.linno, of_node (n.nredir.n), redirs (n.nredir.redirect)]);
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 139, in of_node
    return ["While", of_binary (n)];
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 229, in of_binary
    return [of_node (n.nbinary.ch1), of_node (n.nbinary.ch2)];
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 91, in of_node
    to_args (n.ncmd.args),
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 560, in to_args
    arg = to_arg (n.contents.narg);
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 237, in to_arg
    a = parse_arg (s, bqlist, stack);
  File "/home/tammam1/pash/compiler/parser/ceda/ast2a.py", line 318, in parse_arg
    os.abort ();
NameError: name 'os' is not defined

```

**Comment by angelhof** [comment]
This might not be POSIX parseable. @thurstond, @mgree any idea?

**Comment by mgree** [comment]
That's perfectly valid POSIX, but you won't be happy with what it means: dash, say, is going to parse the lvalue of the assignment as a command.

**Comment by angelhof** [comment]
🥲

**Comment by angelhof** [comment]
Wontfix (since we are using a dash parsing library)
