### ISSUE TITLE
self.running_procs becomes negative, leading to AssertionError

### ISSUE THREAD

**Issue by BolunThompson** [binpash/pash#736]
Possibly low priority since I only found the problem while fixing another bug. Minimal test case:
```sh
echo "abc" > /tmp/data.txt
cat /tmp/data.txt
echo
echo
echo
```

Exception:
```python
Traceback (most recent call last):
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 535, in <module>
    main()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 531, in main
    scheduler.run()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 510, in run
    self.parse_and_run_cmd(input_cmd)
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 444, in parse_and_run_cmd
    response = self.compile_and_add(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 289, in compile_and_add
    self.wait_unsafe()
  File "/home/bolun/pash/compiler/pash_compilation_server.py", line 433, in wait_unsafe
    assert self.running_procs == 1
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Checking if self.running_procs already equals zero before decrementing it in `remove_process` does solve the immediate issue, but ideally the number should already match up.

**Comment by BolunThompson** [comment]
Looking at this again, this works on the ubuntu 20.04 container (vs the 24.04 system I develop on). Perhaps caused by different bash versions?
